# Generated by Django 4.2.5 on 2025-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_alter_carousel_contenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeintro',
            name='intro_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
