# Generated by Django 4.2.5 on 2025-07-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IconsenggRaqForm',
            new_name='RaqForm',
        ),
    ]
