# Generated by Django 4.2.5 on 2025-07-29 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedetails',
            name='seo_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagedetails',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
