# Generated by Django 4.2.5 on 2025-08-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesAdministration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedetails',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
