# Generated by Django 4.2.5 on 2025-07-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0002_services_pagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeature',
            name='services_page_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='menu_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='page_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_postion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='accordion_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
