# Generated by Django 4.2.5 on 2025-08-06 17:07

import common.BaseModel
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.file_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternitivetext', models.CharField(blank=True, max_length=255)),
                ('image_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_description', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=100, null=True)),
                ('Views', models.CharField(blank=True, max_length=100, null=True)),
                ('Downloads', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('imageDimension', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image_WebURL', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(blank=True, null=True, upload_to=common.BaseModel.file_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('alternitivetext', models.CharField(blank=True, max_length=255)),
                ('image_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_description', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.CharField(blank=True, max_length=100, null=True)),
                ('Views', models.CharField(blank=True, max_length=100, null=True)),
                ('Downloads', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('imageDimension', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('video_WebURL', models.URLField(blank=True, null=True)),
                ('video_id', models.CharField(blank=True, max_length=50)),
                ('video_thumbnail_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
